default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-docstring-first
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.4
  hooks:
    - id: autopep8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      additional_dependencies: [
        flake8-isort,
        flake8-blind-except,
        flake8-builtins,
        flake8-logging-format,
      ]
      args: ["--config=tox.ini"]
